name: Code Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # PHPコードチェック
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
      - name: Install PHP dependencies
        run: composer install
      - name: Get Changed PHP Files
        id: changed-php
        run: |
          git fetch --depth=2 origin
          RESULT=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep '\.php$' || echo "")
          echo "files=$RESULT" >> $GITHUB_ENV
      - name: Run PHPCS
        if: env.files != ''
        run: |
          echo "$files" | tr '\n' ' ' | xargs ./vendor/bin/phpcs --standard=PSR12

      # JavaScriptコードチェック
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Node.js dependencies
        run: npm install
      - name: Get Changed JS Files
        id: changed-js
        run: |
          git fetch --depth=2 origin
          RESULT=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep '\.js$' || echo "")
          echo "files=$RESULT" >> $GITHUB_ENV
      - name: Run ESLint
        if: env.files != ''
        run: |
          echo "$files" | tr '\n' ' ' | xargs npx eslint
