name: Code Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # PHPコードチェック
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
      - name: Install PHP dependencies
        run: composer install
      - name: Get Changed PHP Files
        id: changed-php
        run: |
          git fetch --depth=2 origin
          git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep '\.php$' || echo ""
      - name: Run PHPCS
        if: steps.changed-php.outputs.files != ''
        run: |
          echo "${{ steps.changed-php.outputs.files }}" | tr '\n' ' ' | xargs ./vendor/bin/phpcs --standard=PSR12

      # JavaScriptコードチェック
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Node.js dependencies
        run: npm install
      - name: Get Changed JS Files
        id: changed-js
        run: |
          git fetch --depth=2 origin
          git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep '\.js$' || echo ""
        outputs:
          files: ${{ steps.changed-js.outputs.files }}
      - name: Run ESLint
        if: steps.changed-js.outputs.files != ''
        run: |
          echo "${{ steps.changed-js.outputs.files }}" | tr '\n' ' ' | xargs npx eslint
